---
sidebar: sidebar 
permalink: concept_api_rest.html 
keywords: rest api, deploy rest api, rest, architecture, resources, state, uri, http, json 
summary: 'A Transferência de Estado Representacional (REST) é um estilo para a criação de aplicações web distribuídas. Quando aplicada ao design de uma API de serviços web, ela estabelece um conjunto de tecnologias e práticas recomendadas para expor recursos baseados em servidor e gerenciar seus estados. Ela utiliza protocolos e padrões tradicionais para fornecer uma base flexível para a implantação e o gerenciamento de clusters ONTAP Select .' 
---
= Base de serviços web REST para implantação e gerenciamento de clusters ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A Transferência de Estado Representacional (REST) é um estilo para a criação de aplicações web distribuídas. Quando aplicada ao design de uma API de serviços web, ela estabelece um conjunto de tecnologias e práticas recomendadas para expor recursos baseados em servidor e gerenciar seus estados. Ela utiliza protocolos e padrões tradicionais para fornecer uma base flexível para a implantação e o gerenciamento de clusters ONTAP Select .



== Arquitetura e restrições clássicas

O conceito REST foi formalmente articulado por Roy Fielding em seu doutorado. https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm["dissertação"] na UC Irvine em 2000. Ela define um estilo arquitetônico por meio de um conjunto de restrições que, coletivamente, aprimoram aplicações web e os protocolos subjacentes. As restrições estabelecem uma aplicação de serviços web RESTful baseada em uma arquitetura cliente/servidor, utilizando um protocolo de comunicação sem estado.



== Recursos e representação estatal

Os recursos são os componentes básicos de um sistema web. Ao criar uma aplicação de serviços web REST, as tarefas iniciais de design incluem:

* Identificação de recursos baseados em sistema ou servidor. Todo sistema utiliza e mantém recursos. Um recurso pode ser um arquivo, uma transação comercial, um processo ou uma entidade administrativa. Uma das primeiras tarefas ao projetar uma aplicação baseada em serviços web REST é identificar os recursos.
* Definição de estados de recursos e operações de estado associadas. Os recursos estão sempre em um de um número finito de estados. Os estados, bem como as operações associadas usadas para afetar as mudanças de estado, devem ser claramente definidos.


As mensagens são trocadas entre o cliente e o servidor para acessar e alterar o estado dos recursos de acordo com o modelo genérico CRUD (Criar, Ler, Atualizar e Excluir).



== Pontos finais de URI

Cada recurso REST deve ser definido e disponibilizado usando um esquema de endereçamento bem definido. Os endpoints onde os recursos estão localizados e identificados usam um Identificador Uniforme de Recursos (URI). O URI fornece uma estrutura geral para a criação de um nome exclusivo para cada recurso na rede. O Localizador Uniforme de Recursos (URL) é um tipo de URI usado com serviços web para identificar e acessar recursos. Os recursos são normalmente expostos em uma estrutura hierárquica semelhante a um diretório de arquivos.



== Mensagens HTTP

O Protocolo de Transferência de Hipertexto (HTTP) é o protocolo usado pelo cliente e servidor de serviços web para trocar mensagens de solicitação e resposta sobre os recursos. Como parte do projeto de um aplicativo de serviços web, verbos HTTP (como GET e POST) são mapeados para os recursos e as ações de gerenciamento de estado correspondentes.

O HTTP não possui estado. Portanto, para associar um conjunto de solicitações e respostas relacionadas em uma única transação, informações adicionais devem ser incluídas nos cabeçalhos HTTP transmitidos com os fluxos de dados de solicitação/resposta.



== Formatação JSON

Embora as informações possam ser estruturadas e transferidas entre um cliente e um servidor de diversas maneiras, a opção mais popular (e a usada com a API REST do Deploy) é a JavaScript Object Notation (JSON). JSON é um padrão do setor para representar estruturas de dados simples em texto simples e é usado para transferir informações de estado que descrevem os recursos.
