---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: Primeiro, familiarize-se com os conceitos gerais de rede aplicáveis ao ambiente ONTAP Select . Em seguida, explore as características e opções específicas disponíveis com os clusters de nó único e de vários nós. 
---
= Conceitos e características de rede ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Primeiro, familiarize-se com os conceitos gerais de rede aplicáveis ao ambiente ONTAP Select . Em seguida, explore as características e opções específicas disponíveis com os clusters de nó único e de vários nós.



== Rede física

A rede física suporta uma implantação de cluster ONTAP Select principalmente fornecendo a infraestrutura de comutação de camada 2 subjacente. A configuração relacionada à rede física inclui tanto o host do hipervisor quanto o ambiente de rede comutada mais amplo.



=== Opções de NIC do host

Cada host do hipervisor ONTAP Select deve ser configurado com duas ou quatro portas físicas. A configuração exata que você escolher dependerá de vários fatores, incluindo:

* Se o cluster contém um ou vários hosts ONTAP Select
* Qual sistema operacional do hipervisor é usado
* Como o switch virtual é configurado
* Se o LACP é usado com os links ou não




=== Configuração do switch físico

Você deve garantir que a configuração dos switches físicos seja compatível com a implantação do ONTAP Select . Os switches físicos são integrados aos switches virtuais baseados em hipervisor. A configuração exata que você escolher depende de vários fatores. As principais considerações incluem o seguinte:

* Como você manterá a separação entre as redes interna e externa?
* Você manterá uma separação entre as redes de dados e de gerenciamento?
* Como as VLANs da camada dois serão configuradas?




== Rede lógica

O ONTAP Select utiliza duas redes lógicas diferentes, separando o tráfego por tipo. Especificamente, o tráfego pode fluir entre os hosts dentro do cluster, bem como para os clientes de armazenamento e outras máquinas fora do cluster. Os switches virtuais gerenciados pelos hipervisores ajudam a dar suporte à rede lógica.



=== Rede interna

Em uma implantação de cluster com vários nós, os nós individuais do ONTAP Select se comunicam por meio de uma rede "interna" isolada. Essa rede não fica exposta nem disponível fora dos nós do cluster ONTAP Select .


NOTE: A rede interna só está presente em um cluster de vários nós.

A rede interna tem as seguintes características:

* Usado para processar tráfego intracluster ONTAP , incluindo:
+
** Conjunto
** Interconexão de alta disponibilidade (HA-IC)
** Espelho de sincronização RAID (RSM)


* Rede de camada única e dois baseada em uma VLAN
* Endereços IP estáticos são atribuídos pelo ONTAP Select:
+
** Somente IPv4
** DHCP não utilizado
** Endereço link-local


* O tamanho da MTU é de 9000 bytes por padrão e pode ser ajustado dentro do intervalo de 7500-9000 (inclusive)




=== Rede externa

A rede externa processa o tráfego entre os nós de um cluster ONTAP Select e os clientes de armazenamento externo, bem como as outras máquinas. A rede externa faz parte de cada implantação de cluster e possui as seguintes características:

* Usado para processar tráfego ONTAP , incluindo:
+
** Dados (NFS, CIFS, iSCSI)
** Gerenciamento (cluster e nó; opcionalmente SVM)
** Intercluster (opcional)


* Suporta opcionalmente VLANs:
+
** Grupo de portas de dados
** Grupo de portos de gestão


* Endereços IP atribuídos com base nas escolhas de configuração do administrador:
+
** IPv4 ou IPv6


* O tamanho da MTU é 1500 bytes por padrão (pode ser ajustado)


A rede externa está presente com clusters de todos os tamanhos.



== Ambiente de rede de máquina virtual

O host do hipervisor fornece vários recursos de rede.

O ONTAP Select depende dos seguintes recursos expostos pela máquina virtual:

Portas de máquina virtual:: Há várias portas disponíveis para uso pelo ONTAP Select. Elas são atribuídas e utilizadas com base em diversos fatores, incluindo o tamanho do cluster.
Comutador virtual:: O software do switch virtual no ambiente do hipervisor, seja vSwitch (VMware) ou Open vSwitch (KVM), conecta as portas expostas pela máquina virtual às portas físicas da placa de rede Ethernet. Você deve configurar um vSwitch para cada host ONTAP Select , conforme apropriado para o seu ambiente.

