---
sidebar: sidebar 
permalink: concept_api_operation.html 
keywords: rest api, deploy rest api, rest, operation, basic operation 
summary: Embora o REST estabeleça um conjunto comum de tecnologias e práticas recomendadas, os detalhes de cada API podem variar de acordo com as escolhas de design. Você deve estar ciente dos detalhes e das características operacionais da API ONTAP Select Deploy antes de usá-la. 
---
= Características operacionais básicas da API ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Embora o REST estabeleça um conjunto comum de tecnologias e práticas recomendadas, os detalhes de cada API podem variar de acordo com as escolhas de design. Você deve estar ciente dos detalhes e das características operacionais da API ONTAP Select Deploy antes de usá-la.



== Host do hipervisor versus ONTAP Select

Um _host hipervisor_ é a plataforma de hardware central que hospeda uma máquina virtual ONTAP Select . Quando uma máquina virtual ONTAP Select é implantada e está ativa em um host hipervisor, a máquina virtual é considerada um _nó ONTAP Select_. Com a versão 3 da API REST de Implantação, os objetos host e nó são separados e distintos. Isso permite um relacionamento um-para-muitos, em que um ou mais nós ONTAP Select podem ser executados no mesmo host hipervisor.



== Identificadores de objetos

Cada instância de recurso ou objeto recebe um identificador exclusivo quando é criado. Esses identificadores são globalmente exclusivos dentro de uma instância específica do ONTAP Select Deploy. Após emitir uma chamada de API que cria uma nova instância de objeto, o valor do ID associado é retornado ao chamador no `location` cabeçalho da resposta HTTP. Você pode extrair o identificador e usá-lo em chamadas subsequentes ao se referir à instância do recurso.


NOTE: O conteúdo e a estrutura interna dos identificadores de objeto podem mudar a qualquer momento. Você deve usar os identificadores somente nas chamadas de API aplicáveis, conforme necessário, ao se referir aos objetos associados.



== Identificadores de solicitação

Cada solicitação de API bem-sucedida recebe um identificador exclusivo. O identificador é retornado em `request-id` cabeçalho da resposta HTTP associada. Você pode usar um identificador de solicitação para se referir coletivamente às atividades de uma única transação de solicitação-resposta de API específica. Por exemplo, você pode recuperar todas as mensagens de eventos de uma transação com base no ID da solicitação.



== Chamadas síncronas e assíncronas

Há duas maneiras principais pelas quais um servidor executa uma solicitação HTTP recebida de um cliente:

* Síncrono O servidor executa a solicitação imediatamente e responde com um código de status 200, 201 ou 204.
* Assíncrono: O servidor aceita a solicitação e responde com o código de status 202. Isso indica que o servidor aceitou a solicitação do cliente e iniciou uma tarefa em segundo plano para concluí-la. O sucesso ou a falha final não são imediatamente conhecidos e devem ser determinados por meio de chamadas de API adicionais.




== Confirmar a conclusão de um trabalho de longa duração

Geralmente, qualquer operação que possa levar muito tempo para ser concluída é processada de forma assíncrona usando uma tarefa em segundo plano no servidor. Com a API REST de Implantação, cada tarefa em segundo plano é ancorada por um objeto Job, que rastreia a tarefa e fornece informações, como o estado atual. Um objeto Job, incluindo seu identificador exclusivo, é retornado na resposta HTTP após a criação de uma tarefa em segundo plano.

Você pode consultar o objeto Job diretamente para determinar o sucesso ou a falha da chamada de API associada. Consulte _processamento assíncrono usando o objeto Job_ para obter mais informações.

Além de usar o objeto Job, há outras maneiras de determinar o sucesso ou a falha de uma solicitação, incluindo:

* Mensagens de evento: Você pode recuperar todas as mensagens de evento associadas a uma chamada de API específica usando o ID da solicitação retornado com a resposta original. As mensagens de evento geralmente contêm uma indicação de sucesso ou falha e também podem ser úteis na depuração de uma condição de erro.
* Estado ou status do recurso Vários recursos mantêm um valor de estado ou status que você pode consultar para determinar indiretamente o sucesso ou a falha de uma solicitação.




== Segurança

A API de implantação usa as seguintes tecnologias de segurança:

* Segurança da Camada de Transporte: Todo o tráfego enviado pela rede entre o servidor de implantação e o cliente é criptografado por TLS. O uso do protocolo HTTP em um canal não criptografado não é suportado. A versão 1.2 do TLS é suportada.
* Autenticação HTTP: A autenticação básica é usada para todas as transações da API. Um cabeçalho HTTP, que inclui o nome de usuário e a senha em uma string base64, é adicionado a cada solicitação.

