---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: Você pode adquirir uma licença ONTAP Select Capacity Tier ou Capacity Pool em um dos três níveis de capacidade da plataforma. Essas ofertas de licença determinam os recursos dos hosts onde você implementa o ONTAP Select. 
---
= Saiba mais sobre as ofertas de licença de plataforma para o ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode adquirir uma licença ONTAP Select Capacity Tier ou Capacity Pool nos níveis Standard, Premium ou Premium XL. Essas ofertas de licença determinam os recursos dos hosts onde você implementa o ONTAP Select.



== O que uma oferta de licença de plataforma fornece

Uma oferta de licença específica determina as capacidades do host do hipervisor em duas áreas:

* Tipo de instância (CPU, memória)
* Características adicionais


As ofertas de licença são organizadas em ordem crescente de recursos, do padrão ao premium XL. Em geral, a opção de licença escolhida concede os recursos daquele nível e de todos os níveis inferiores. Por exemplo, o nível premium oferece os recursos premium e padrão.

A tabela a seguir compara os recursos das licenças padrão, premium e premium XL.

[cols="25,25,25,25,25"]
|===
2+| A licença suporta... | Padrão | Prêmio | Premium XL 


2+| Tipo de instância | Somente pequeno | Pequeno ou médio | Pequeno, médio ou grande 


.2+| Unidades de disco rígido (HDD) em um ... | Configuração RAID por hardware | Sim | Sim | Sim 


| Configuração do vNAS | Sim | Sim | Sim 


.3+| Unidades de estado sólido (SSD) em um ... | Configuração RAID por hardware | Não | Sim | Sim 


| Configuração RAID por software | Não | Sim | Sim 


| Configuração do vNAS | Sim | Sim | Sim 


.3+| Unidades NVMe em um ... | Configuração RAID por hardware | Não | Não | Sim 


| Configuração RAID por software | Não | Não | Sim 


| Configuração do vNAS | Sim | Sim | Sim 


2+| SDS do MetroCluster | Não | Sim | Sim 
|===

NOTE: As máquinas virtuais baseadas em kernel (KVM) não suportam o tipo de instância grande.



== Compare o suporte de hardware para ofertas de licença de plataforma

As ofertas de licenças padrão, premium e premium XL oferecem suporte a uma ampla gama de hardware e software. Para obter informações atualizadas sobre versões de hardware e software, consulte olink:https://mysupport.netapp.com/matrix/["Ferramenta de Matriz de Interoperabilidade"^] .

[role="tabbed-block"]
====
.Item principal
--
[cols="5"30"]
|===


2+| Tipo de item principal 3+| Descrição 


2+| Protocolos de host 3+| NFS, SMB/CIFS, iSCSI e NVMe sobre TCP 


2+| Opções de implantação 3+| Nó único Cluster de dois nós (par HA) Cluster de quatro, seis ou oito nós 


2+| Capacidade suportada (por nó) 3+| Até 400 TB de dados brutos (ESXi e KVM) 
|===
--
.Hardware
--
[cols="5"30"]
|===


2+| Tipo de hardware 3+| Descrição 


2+| Tamanho da instância | Pequeno | Médio | Grande 


2+| Família de CPU | Intel Xeon E5-26xx v3 (Haswell) ou posterior | Intel Xeon E5-26xx v3 (Haswell) ou posterior | Intel Xeon E5-26xx v3 (Haswell) ou posterior 


2+| ONTAP Select CPU/memória | 4 CPUs virtuais (vCPUs) / 16 GB de RAM | 8 vCPUs / 64 GB de RAM | 16 vCPUs / 128 GB de RAM 


2+| Requisitos mínimos de CPU/memória do host ^1^ | 6 núcleos / 24 GB de RAM | 10 núcleos / 72 GB de RAM | 18 núcleos / 136 GB de RAM 


2+| Rede (por nó) 3+| Mínimo de duas portas de 1 GbE para um cluster de nó único Mínimo de quatro portas de 1 GbE para um cluster de dois nós (par HA) Mínimo de duas portas de 10 GbE para um cluster de quatro, seis ou oito nós 
|===
^1^ Assume dois núcleos e 8 GB de RAM para o hipervisor.

--
.Tipo de armazenamento
--
A tabela a seguir fornece o tipo mínimo de licença necessária para o armazenamento especificado. 

[cols="5"30"]
|===


2+| Tipo de armazenamento 3+| Descrição 


2+| Tipo de licença | Padrão | Prêmio | Premium XL 


2+| Tamanho da instância | Pequeno | Pequeno e médio | Pequeno, médio e grande 


2+| DAS local com controlador RAID de hardware | 8 - 60 unidades | 8 - 60 unidades | 8 - 60 unidades 


2+| HDD (SAS, NL-SAS, SATA) | Não aplicável | 4 – 60 unidades | 4 – 60 unidades 


2+| SSD (SAS) | Não aplicável | 4 – 60 unidades (somente SSD) | 4 – 60 unidades (somente SSD) 


2+| DAS local com RAID de software | Não aplicável | Aplicável | 4 a 14 unidades (somente NVMe) 


2+| Matrizes externas ^1^ 3+| Os datastores hospedados em arrays externos são conectados por meio de FC, FCoE, iSCSI e NFS (NFS não é compatível com KVM). Esses datastores oferecem alta disponibilidade e resiliência. 
|===
^1^ O suporte ao protocolo de matriz externa reflete a conectividade de armazenamento em rede.

--
.Software
--
[cols="5"30"]
|===


2+| Tipo de software 3+| Descrição 


2+| Suporte a hipervisor (VMware) 3+| VMware vSphere 9.0, VMware vSphere 8.0GA e atualizações 1 a 3, VMware vSphere 7.0GA e atualizações 1 a 3C 


2+| Suporte a hipervisor (KVM)  a| 
Red Hat Enterprise Linux (RHEL) 64-bit (KVM) 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 e 8.6

Rocky Linux (KVM) 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 e 8.6

*Nota*: Existem limitações no fluxo de trabalho RAID por software para hipervisores KVM em hosts RHEL 10.1 e 10.0 e Rocky Linux 10.1 e 10.0. Para mais informações, consulte os seguintes artigos da Knowledge Base:

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: Mensagem de aviso ao criar o Cluster HWR usando RHEL 10 e ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: Pools de armazenamento e discos de armazenamento não visíveis para SWR na página de criação de cluster em hosts com RHEL10/Rocky 10"^]




2+| Software de gestão 3+| Conjunto de gerenciamento NetApp Active IQ Unified Manager ONTAP Select Deploy Utility SnapCenter (opcional) 
|===
--
====
.Informações relacionadas
* link:concept_lic_production.html["Saiba mais sobre os tipos de licença Capacity Tier e Capacity Pool"]

