---
sidebar: sidebar 
permalink: concept_perf_general.html 
keywords: ontap select, performance 
summary: O desempenho de um cluster ONTAP Select pode variar dependendo da configuração de hardware. 
---
= Visão geral do desempenho do ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O desempenho de um cluster ONTAP Select pode variar consideravelmente devido às características do hardware e da configuração subjacentes. A configuração específica do hardware é o fator mais importante no desempenho de uma instância específica do ONTAP Select . Aqui estão alguns dos fatores que afetam o desempenho de uma instância específica do ONTAP Select :

* *Frequência central*. Em geral, uma frequência mais alta é preferível.
* *Soquete único versus multisocket*. O ONTAP Select não utiliza recursos multisocket, mas a sobrecarga do hipervisor para suportar configurações multisocket é responsável por algum desvio no desempenho total.
* *Configuração da placa RAID e driver do hipervisor associado*. O driver padrão fornecido pelo hipervisor pode precisar ser substituído pelo driver do fornecedor do hardware.
* *Tipo de unidade e número de unidades no(s) grupo(s) RAID*.
* *Versão do hipervisor e nível de patch*.

