---
sidebar: sidebar 
permalink: concept_nw_internal_external.html 
keywords: ontap select, internal network, external network 
summary: Características das redes ONTAP Select internas e externas. 
---
= ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Características das redes internas e externas do ONTAP Select .



== ONTAP Select

A rede interna do ONTAP Select , presente apenas na versão multinó do produto, é responsável por fornecer ao cluster ONTAP Select serviços de comunicação de cluster, interconexão de alta disponibilidade e replicação síncrona. Essa rede inclui as seguintes portas e interfaces:

* *e0c, e0d.* Hospedagem de LIFs de rede de cluster
* *e0e.* Hospedando o RSM LIF
* *e0f.* Hospedando o LIF de interconexão HA


A taxa de transferência e a latência desta rede são cruciais para determinar o desempenho e a resiliência do cluster ONTAP Select . O isolamento da rede é necessário para a segurança do cluster e para garantir que as interfaces do sistema sejam mantidas separadas do restante do tráfego da rede. Portanto, esta rede deve ser usada exclusivamente pelo cluster ONTAP Select .


NOTE: Não há suporte para o uso da rede interna Select para tráfego diferente do tráfego do cluster Select, como tráfego de aplicativos ou de gerenciamento. Não pode haver outras VMs ou hosts na VLAN interna do ONTAP .

Os pacotes de rede que trafegam pela rede interna devem estar em uma rede dedicada de camada 2 com marcação VLAN. Isso pode ser feito executando uma das seguintes tarefas:

* Atribuição de um grupo de portas com tags VLAN às NICs virtuais internas (e0c a e0f) (modo VST)
* Usando a VLAN nativa fornecida pelo switch upstream, onde a VLAN nativa não é usada para nenhum outro tráfego (atribuir um grupo de portas sem ID de VLAN, ou seja, modo EST)


Em todos os casos, a marcação de VLAN para tráfego de rede interno é feita fora da VM ONTAP Select .


NOTE: Somente vSwitches padrão e distribuídos do ESX são suportados. Outros switches virtuais ou conectividade direta entre hosts ESX não são suportados. A rede interna deve estar totalmente aberta; NAT ou firewalls não são suportados.

Em um cluster ONTAP Select , o tráfego interno e o tráfego externo são separados por meio de objetos de rede virtuais da camada 2, conhecidos como grupos de portas. A atribuição adequada desses grupos de portas pelo vSwitch é extremamente importante, especialmente para a rede interna, responsável por fornecer serviços de cluster, interconexão de alta disponibilidade e replicação de espelho. Largura de banda insuficiente para essas portas de rede pode causar degradação do desempenho e até mesmo afetar a estabilidade do nó do cluster. Portanto, clusters de quatro, seis e oito nós exigem que a rede interna do ONTAP Select utilize conectividade de 10 Gb; placas de rede de 1 Gb não são suportadas. No entanto, compensações podem ser feitas para a rede externa, pois limitar o fluxo de dados de entrada para um cluster ONTAP Select não afeta sua capacidade de operar de forma confiável.

Um cluster de dois nós pode usar quatro portas de 1 Gb para tráfego interno ou uma única porta de 10 Gb em vez das duas portas de 10 Gb exigidas pelo cluster de quatro nós. Em um ambiente em que as condições impeçam o servidor de receber quatro placas de rede de 10 Gb, duas placas de rede de 10 Gb podem ser usadas para a rede interna e duas placas de rede de 1 Gb podem ser usadas para a rede ONTAP externa.



=== Validação e solução de problemas de rede interna

A rede interna em um cluster multinó pode ser validada usando a funcionalidade de verificação de conectividade de rede. Essa função pode ser invocada a partir da CLI de implantação em execução. `network connectivity-check start` comando.

Execute o seguinte comando para visualizar a saída do teste:

[listing]
----
network connectivity-check show --run-id X (X is a number)
----
Esta ferramenta é útil apenas para solucionar problemas de rede interna em um cluster Select de vários nós. A ferramenta não deve ser usada para solucionar problemas de clusters de nó único (incluindo configurações de vNAS), conectividade do ONTAP Deploy com o ONTAP Select ou problemas de conectividade do lado do cliente.

O assistente de criação de cluster (parte da interface de usuário do ONTAP Deploy) inclui o verificador de rede interno como uma etapa opcional disponível durante a criação de clusters multinós. Dada a importância da rede interna em clusters multinós, incluir essa etapa no fluxo de trabalho de criação de clusters melhora a taxa de sucesso das operações de criação de clusters.

A partir do ONTAP Deploy 2.10, o tamanho da MTU usada pela rede interna pode ser definido entre 7.500 e 9.000. O verificador de conectividade de rede também pode ser usado para testar tamanhos de MTU entre 7.500 e 9.000. O valor padrão da MTU é definido como o valor do switch de rede virtual. Esse valor padrão teria que ser substituído por um valor menor se uma sobreposição de rede, como VXLAN, estivesse presente no ambiente.



== ONTAP Select

A rede externa do ONTAP Select é responsável por todas as comunicações de saída do cluster e, portanto, está presente tanto nas configurações de nó único quanto nas de vários nós. Embora essa rede não tenha os requisitos de taxa de transferência rigorosamente definidos da rede interna, o administrador deve ter cuidado para não criar gargalos de rede entre o cliente e a VM do ONTAP , pois problemas de desempenho podem ser erroneamente caracterizados como problemas do ONTAP Select .


NOTE: De forma semelhante ao tráfego interno, o tráfego externo pode ser marcado na camada vSwitch (VST) e na camada de switch externo (EST). Além disso, o tráfego externo pode ser marcado pela própria VM ONTAP Select em um processo conhecido como VGT. Veja a seçãolink:concept_nw_data_mgmt_separation.html["Separação de tráfego de dados e gerenciamento"] Para obter mais detalhes.

A tabela a seguir destaca as principais diferenças entre as redes interna e externa do ONTAP Select .

*Referência rápida de rede interna versus externa*

[cols="3*"]
|===
| Descrição | Rede interna | Rede externa 


| Serviços de rede | Cluster HA/IC RAID SyncMirror (RSM) | Gerenciamento de dados Intercluster (SnapMirror e SnapVault) 


| Isolamento de rede | Obrigatório | Opcional 


| Tamanho do quadro (MTU) | 7.500 a 9.000 | 1.500 (padrão) 9.000 (com suporte) 


| Atribuição de endereço IP | Gerado automaticamente | Definido pelo usuário 


| Suporte DHCP | Não | Não 
|===


=== Agrupamento de NIC

Para garantir que as redes interna e externa tenham as características de largura de banda e resiliência necessárias para fornecer alto desempenho e tolerância a falhas, recomenda-se o agrupamento de adaptadores de rede física. Configurações de cluster de dois nós com um único link de 10 Gb são suportadas. No entanto, a prática recomendada pela NetApp é usar o agrupamento de NICs nas redes interna e externa do cluster ONTAP Select .



=== Geração de endereço MAC

Os endereços MAC atribuídos a todas as portas de rede do ONTAP Select são gerados automaticamente pelo utilitário de implantação incluído. O utilitário utiliza um identificador organizacional exclusivo (OUI) específico da plataforma e da NetApp para garantir que não haja conflito com os sistemas FAS . Uma cópia desse endereço é então armazenada em um banco de dados interno na VM de instalação do ONTAP Select (ONTAP Deploy) para evitar reatribuições acidentais durante futuras implantações de nós. Em nenhum momento o administrador deve modificar o endereço MAC atribuído a uma porta de rede.
