---
sidebar: sidebar 
permalink: concept_api_understanding_scripts.html 
keywords: rest api, deploy rest api, rest, python, python scripts, understanding 
summary: Os scripts Python de exemplo permitem que você execute diversas tarefas diferentes. Você deve entender os scripts antes de usá-los em uma instância de implantação ativa. 
---
= Entenda os scripts Python para ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Os scripts Python de exemplo permitem que você execute diversas tarefas diferentes. Você deve entender os scripts antes de usá-los em uma instância de implantação ativa.



== Características comuns de design

Os scripts foram projetados com as seguintes características comuns:

* Executar a partir da interface de linha de comando em uma máquina cliente. Você pode executar os scripts Python em qualquer máquina cliente configurada corretamente. Consulte _Antes de começar_ para obter mais informações.
* Aceitar parâmetros de entrada da CLI Cada script é controlado na CLI por meio de parâmetros de entrada.
* Ler arquivo de entrada: Cada script lê um arquivo de entrada com base em sua finalidade. Ao criar ou excluir um cluster, você deve fornecer um arquivo de configuração JSON. Ao adicionar uma licença de nó, você deve fornecer um arquivo de licença válido.
* Use um módulo de suporte comum. O módulo de suporte comum _deploy_requests.py_ contém uma única classe. Ele é importado e usado por cada um dos scripts.




== Crie um cluster

Você pode criar um cluster ONTAP Select usando o script cluster.py. Com base nos parâmetros da CLI e no conteúdo do arquivo de entrada JSON, você pode modificar o script para o seu ambiente de implantação da seguinte maneira:

* Hipervisor: você pode implantar no ESXI ou KVM (dependendo da versão de implantação). Ao implantar no ESXi, o hipervisor pode ser gerenciado pelo vCenter ou pode ser um host autônomo.
* Tamanho do cluster Você pode implantar um cluster de nó único ou de vários nós.
* Licença de avaliação ou produção Você pode implantar um cluster com uma licença de avaliação ou adquirida para produção.


Os parâmetros de entrada da CLI para o script incluem:

* Nome do host ou endereço IP do servidor de implantação
* Senha para a conta de usuário administrador
* Nome do arquivo de configuração JSON
* Sinalizador detalhado para saída de mensagem




== Adicionar uma licença de nó

Se optar por implantar um cluster de produção, você deverá adicionar uma licença para cada nó usando o script _add_license.py_. Você pode adicionar a licença antes ou depois de implantar o cluster.

Os parâmetros de entrada da CLI para o script incluem:

* Nome do host ou endereço IP do servidor de implantação
* Senha para a conta de usuário administrador
* Nome do arquivo de licença
* Nome de usuário ONTAP com privilégios para adicionar a licença
* Senha para o usuário ONTAP




== Excluir um cluster

Você pode excluir um cluster ONTAP Select existente usando o script _delete_cluster.py_.

Os parâmetros de entrada da CLI para o script incluem:

* Nome do host ou endereço IP do servidor de implantação
* Senha para a conta de usuário administrador
* Nome do arquivo de configuração JSON

