---
sidebar: sidebar 
permalink: concept_terminology.html 
keywords: terminology, key concepts, concepts 
summary: Ao começar a explorar o ONTAP Select e planejar uma implantação, é útil primeiro se familiarizar com a terminologia e os principais conceitos. 
---
= Terminologia e conceitos-chave do ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ao começar a explorar o ONTAP Select e planejar uma implantação, é útil primeiro se familiarizar com a terminologia e os principais conceitos.

ONTAP Select Implantar:: ONTAP Select Deploy é o utilitário de administração usado para implantar clusters ONTAP Select . O utilitário Deploy é executado em uma máquina virtual Linux dedicada. Você pode acessá-lo por meio da interface de usuário web, do shell de gerenciamento CLI e da API REST.
Máquina Virtual baseada em Kernel:: A Máquina Virtual baseada em Kernel (KVM) é um recurso de virtualização do kernel Linux, que permite que ele atue como uma plataforma de hipervisor. Uma ampla gama de sistemas operacionais convidados é suportada.
Host do hipervisor versus ONTAP Select:: Um _host hipervisor_ é a plataforma de hardware central que hospeda uma máquina virtual ONTAP Select . Quando uma máquina virtual ONTAP Select é implantada e está ativa em um host hipervisor, ela é considerada um _nó ONTAP Select_.
Cluster ONTAP Select:: Você pode criar um _cluster ONTAP Select_ composto por um, dois, quatro, seis ou oito nós. Clusters com vários nós sempre contêm um ou mais pares de HA. Por exemplo, um cluster de quatro nós consiste em dois pares de HA. Um cluster com um único nó não oferece capacidade de HA.
Preparação do ambiente do host do hipervisor:: Antes de usar o utilitário de administração Deploy para implantar um cluster ONTAP Select , você precisa preparar os hosts do hipervisor onde o ONTAP Select será executado, incluindo os ambientes de armazenamento e rede. Essa pré-configuração do host é feita fora do produto ONTAP Select, com base nos requisitos e limitações atuais.
Implantações de avaliação versus produção:: Cada nó do ONTAP Select é executado com uma _licença de avaliação_ ou uma _licença adquirida_. Uma licença de avaliação permite que você avalie o ONTAP Select antes de implantá-lo em um ambiente de produção. A licença de avaliação é gerada e aplicada automaticamente. Se você implantar um cluster em um ambiente de produção, precisará adquirir uma licença, o que envolve escolher:
+
--
* Modelo de licenciamento
* Capacidade de armazenamento
* Oferta de licença de plataforma


--
Modelo de licenciamento de níveis de capacidade:: O modelo de licenciamento por Níveis de Capacidade é a opção original para o licenciamento de armazenamento para uma implantação do ONTAP Select . Ele se baseia no modelo ONTAP usado com o NetApp AFF e o FAS. Uma licença separada é necessária para cada nó. A capacidade de armazenamento é bloqueada para o nó e perpétua (sem necessidade de renovação).
Modelo de licenciamento de pools de capacidade:: O modelo de licenciamento de Pools de Capacidade foi introduzido com o ONTAP Select 9.5 usando o Deploy 2.10. Uma licença separada é necessária para cada Pool de Capacidade de armazenamento. A licença do Pool de Capacidade é vinculada a uma instância do License Manager (que é uma instância do Deploy) e deve ser renovada de acordo com os termos da sua compra. Você pode licenciar e usar qualquer número de Pools de Capacidade em sua organização. No entanto, como os Pools de Capacidade são compartilhados pelos nós do ONTAP Select , normalmente são necessárias menos licenças do que o licenciamento por Níveis de Capacidade.
Gerenciador de licenças:: O Gerenciador de Licenças é um componente de software que oferece suporte ao licenciamento de Pools de Capacidade. Atualmente, ele faz parte do utilitário de administração do Deploy. O LM aluga armazenamento para os nós ONTAP Select dos pools compartilhados que gerencia. O _ID de Bloqueio de Licença_ é uma sequência numérica que identifica exclusivamente cada instância do LM e, portanto, cada instância do Deploy. Você deve usar o número de série da licença do Pool de Capacidade e o LLID para gerar um arquivo de licença.
Ofertas de licenças de plataforma:: Há três ofertas de licença disponíveis que determinam os recursos de tamanho da máquina virtual ONTAP Select quando você compra uma licença:
+
--
* Padrão
* Prêmio
* Premium XL


--


Para mais informações, consulte as duas seções _Plano_ e _Licença_.

Pools de armazenamento versus datastores:: Um _pool de armazenamento_ do ONTAP Select é um contêiner de dados lógico projetado para abstrair e ocultar o armazenamento físico subjacente. Um pool de armazenamento é independente do hipervisor. Quando implantado em um host de hipervisor ESXi, o pool de armazenamento do ONTAP Select é sinônimo do _datastore_ do VMware.
MTU de cluster:: O Cluster MTU é um recurso que permite configurar o tamanho da MTU usada na rede interna com um cluster multinós ONTAP Select . O utilitário de administração Deploy ajusta o tamanho da MTU conforme você configura os pares de HA para acomodar seu ambiente de rede. Você também pode definir o valor manualmente.
ONTAP Select vNAS:: A solução ONTAP Select vNAS permite que um nó ONTAP Select acesse datastores VMware em armazenamento externo. Com o ONTAP Select vNAS, um controlador RAID local não é mais necessário; a funcionalidade RAID é assumida como fornecida pelo armazenamento remoto. O ONTAP Select vNAS pode ser configurado das seguintes maneiras:
+
--
* VMware vSAN
* Matriz de armazenamento externo genérica


--


Em ambos os casos, o armazenamento externo deve ser configurado antes de criar um cluster ONTAP Select ou expandir a capacidade de armazenamento de um nó existente.

Rehospedagem de nós na VM ESXi:: Ao implantar um cluster que usa armazenamento externo disponível por meio da solução ONTAP Select vNAS (VMware vSAN ou um array de armazenamento externo genérico), a máquina virtual ESXi que hospeda o nó ONTAP Select pode ser movida por meio de ações que utilizam os seguintes recursos do VMware:
+
--
* vMotion
* Alta Disponibilidade (HA)
* Agendador de Recursos Distribuídos (DRS)
+
O utilitário ONTAP Select Deploy detecta o movimento da máquina virtual como parte da execução de uma operação no cluster, como:

* cluster online
* cluster offline
* adicionar armazenamento
+
Quando uma máquina virtual é movida, o utilitário de implantação atualiza seu banco de dados interno e configura o novo host ESXi. Todas as ações executadas no nó ONTAP Select são bloqueadas até que a movimentação da máquina virtual e as atualizações de implantação sejam concluídas.



--
Abra o vSwitch para KVM:: Open vSwitch (OVS) é uma implementação de software de um switch virtual com suporte a múltiplos protocolos de rede. O OVS é de código aberto e está disponível sob a Licença Apache 2.0.
Serviço de mediação:: O utilitário ONTAP Select Deploy inclui um serviço mediador que se conecta aos nós nos clusters ativos de dois nós. Este serviço monitora cada par de HA e auxilia no gerenciamento de falhas.



CAUTION: Se você tiver um ou mais clusters de dois nós ativos, a máquina virtual ONTAP Select Deploy que administra os clusters deverá estar em execução o tempo todo. Se a máquina virtual Deploy for interrompida, o serviço do mediador ficará indisponível e o recurso de alta disponibilidade será perdido para os clusters de dois nós.

SDS do MetroCluster:: O MetroCluster SDS é um recurso que oferece uma opção de configuração adicional ao implantar um cluster ONTAP Select de dois nós. Ao contrário de uma implantação ROBO típica de dois nós, os nós do MetroCluster SDS podem ser separados por uma distância muito maior. Essa separação física permite casos de uso adicionais, como recuperação de desastres. Você precisa ter uma licença premium ou superior para usar o MetroCluster SDS. Além disso, a rede entre os nós deve suportar um requisito de latência mínima.
Loja de credenciais:: O repositório de credenciais de implantação é um banco de dados seguro que armazena credenciais de conta. Ele é usado principalmente para registrar hosts do hipervisor como parte da criação de um novo cluster. Consulte a seção _Plano_ para obter mais informações.
Eficiência de armazenamento:: O ONTAP Select oferece opções de eficiência de armazenamento semelhantes às opções de eficiência de armazenamento presentes em matrizes FAS e AFF . Conceitualmente, o ONTAP Select com SSDs de armazenamento de conexão direta (DAS) (usando uma licença premium) é semelhante a uma matriz AFF . Configurações que usam DAS com HDDs e todas as configurações vNAS devem ser consideradas semelhantes a uma matriz FAS . A principal diferença entre as duas configurações é que o ONTAP Select com SSDs DAS suporta desduplicação em nível agregado em linha e desduplicação em segundo plano em nível agregado. As demais opções de eficiência de armazenamento estão disponíveis para ambas as configurações.
+
--
As configurações padrão do vNAS habilitam um recurso de otimização de gravação conhecido como registro de dados de instância única (SIDL). Com o ONTAP Select 9.6 e versões posteriores, os recursos de eficiência de armazenamento do ONTAP em segundo plano são qualificados com SIDL habilitado. Consulte a seção _Aprofundamento_ para obter mais informações.

--
Atualização do cluster:: Após criar um cluster, você pode fazer alterações na configuração do cluster ou da máquina virtual fora do utilitário Deploy usando o ONTAP ou as ferramentas de administração do hipervisor. Você também pode migrar uma máquina virtual, o que causa alterações na configuração. Quando essas alterações ocorrem, o utilitário Deploy não é atualizado automaticamente e pode ficar fora de sincronia com o estado do cluster. Você pode usar o recurso de atualização do cluster para atualizar o banco de dados de configuração do Deploy. A atualização do cluster está disponível por meio da interface de usuário web do Deploy, do shell de gerenciamento da CLI e da API REST.
RAID de software:: Ao usar o armazenamento de conexão direta (DAS), a funcionalidade RAID é tradicionalmente fornecida por um controlador RAID de hardware local. Em vez disso, você pode configurar um nó para usar _RAID de software_, onde o nó ONTAP Select fornece a funcionalidade RAID. Se você usar RAID de software, um controlador RAID de hardware não será mais necessário.


[[ontap-select-image-install]]
Instalação de imagem ONTAP Select:: O utilitário de administração Deploy contém apenas uma única versão do ONTAP Select. A versão incluída é a mais atual disponível no momento do lançamento. O recurso de instalação de imagem do ONTAP Select permite adicionar versões anteriores do ONTAP Select à sua instância do utilitário Deploy, que podem ser usadas ao implantar um cluster do ONTAP Select . Verlink:task_cli_deploy_image_add.html["Adicione imagens ONTAP Select para mais informações"] .



NOTE: Você só deve adicionar uma imagem do ONTAP Select com uma versão anterior à versão original incluída na sua instância do Deploy. Adicionar versões posteriores do ONTAP Select sem também atualizar o Deploy não é suportado.

Administrando um cluster ONTAP Select após sua implantação:: Após implantar um cluster ONTAP Select , você pode configurá-lo como faria com um cluster ONTAP baseado em hardware. Por exemplo, você pode configurar um cluster ONTAP Select usando o Gerenciador do Sistema ou a interface de linha de comando padrão do ONTAP .


.Informações relacionadas
link:task_cli_deploy_image_add.html["Adicionar uma imagem ONTAP Select para implantar"]
