---
sidebar: sidebar 
permalink: concept_api_before_workflows.html 
keywords: rest api, deploy rest api, rest, workflows, before you begin 
summary: Você deve se preparar para revisar e usar os processos de fluxo de trabalho. 
---
= Antes de usar os fluxos de trabalho da API ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você deve se preparar para revisar e usar os processos de fluxo de trabalho.



== Entenda as chamadas de API usadas nos fluxos de trabalho

A página de documentação online do ONTAP Select inclui os detalhes de cada chamada de API REST. Em vez de repetir esses detalhes aqui, cada chamada de API usada nos exemplos de fluxo de trabalho inclui apenas as informações necessárias para localizá-la na página de documentação. Após localizar uma chamada de API específica, você pode revisar os detalhes completos da chamada, incluindo os parâmetros de entrada, formatos de saída, códigos de status HTTP e tipo de processamento da solicitação.

As seguintes informações são incluídas para cada chamada de API em um fluxo de trabalho para ajudar a localizar a chamada na página de documentação:

* Categoria As chamadas de API são organizadas na página de documentação em áreas ou categorias funcionalmente relacionadas. Para localizar uma chamada de API específica, role até o final da página e clique na categoria de API aplicável.
* Verbo HTTP O verbo HTTP identifica a ação realizada em um recurso. Cada chamada de API é executada por meio de um único verbo HTTP.
* Caminho O caminho determina o recurso específico ao qual a ação se aplica como parte da execução de uma chamada. A string do caminho é anexada à URL principal para formar a URL completa que identifica o recurso.




== Crie uma URL para acessar diretamente a API REST

Além da página de documentação do ONTAP Select , você também pode acessar a API REST de Implantação diretamente por meio de uma linguagem de programação como Python. Nesse caso, a URL principal é ligeiramente diferente da URL usada para acessar a página de documentação online. Ao acessar a API diretamente, você deve anexar /api à string de domínio e porta. Por exemplo:
`\http://deploy.mycompany.com/api`
