---
sidebar: sidebar 
permalink: concept_api_before_browser.html 
keywords: rest api, deploy rest api, rest, access browser, before you begin 
summary: Há várias coisas que você deve saber antes de usar a página de documentação on-line do Deploy. 
---
= Antes de acessar a API ONTAP Select Deploy com um navegador
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Há várias coisas que você deve saber antes de usar a página de documentação on-line do Deploy.



== Plano de implantação

Se você pretende emitir chamadas de API como parte da execução de tarefas administrativas ou de implantação específicas, considere criar um plano de implantação. Esses planos podem ser formais ou informais e geralmente contêm seus objetivos e as chamadas de API a serem utilizadas. Consulte Processos de fluxo de trabalho usando a API REST de implantação para obter mais informações.



== Exemplos JSON e definições de parâmetros

Cada chamada de API é descrita na página de documentação usando um formato consistente. O conteúdo inclui notas de implementação, parâmetros de consulta e códigos de status HTTP. Além disso, você pode exibir detalhes sobre o JSON usado com as solicitações e respostas da API da seguinte forma:

* Valor de Exemplo: Se você clicar em _Valor de Exemplo_ em uma chamada de API, uma estrutura JSON típica para a chamada será exibida. Você pode modificar o exemplo conforme necessário e usá-lo como entrada para sua solicitação.
* Modelo Se você clicar em _Modelo_, uma lista completa dos parâmetros JSON será exibida, com uma descrição para cada parâmetro.




== Cuidado ao emitir chamadas de API

Todas as operações de API que você realiza usando a página de documentação de Implantação são operações ativas. Tome cuidado para não criar, atualizar ou excluir configurações ou outros dados por engano.
