---
sidebar: sidebar 
permalink: concept_lic_evaluation.html 
keywords: license, licensing, evaluation, upgrade license 
summary: Você pode usar uma licença de avaliação se quiser avaliar o ONTAP Select antes de decidir pela compra. A licença de avaliação está incluída no utilitário de administração do ONTAP Select Deploy e é aplicada automaticamente a cada nó do ONTAP Select como parte de uma implantação de avaliação. 
---
= Licenças de avaliação para implantações do ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode implantar o ONTAP Select com uma licença de avaliação ou uma licença adquirida. A licença escolhida deve ser aplicada a cada um dos nós do cluster ONTAP Select e, portanto, a todo o cluster. Você pode usar uma licença de avaliação se quiser avaliar o ONTAP Select antes de decidir pela compra. A licença de avaliação está incluída no utilitário de administração do ONTAP Select Deploy e é aplicada automaticamente a cada nó do ONTAP Select como parte de uma implantação de avaliação.

[NOTE]
====
Para baixar o utilitário de administração ONTAP Select Deploy, você precisa do seguinte:

* Uma conta registrada no site de suporte da NetApp . Se você não possui uma conta, consulte https://mysupport.netapp.com/site/user/registration["Registro de usuário"^] .
* Para https://mysupport.netapp.com/site/downloads/evaluation/ontap-select["aceitar o contrato de licença do usuário final"^] para uma implementação do ONTAP Select com uma licença de avaliação.


====
Há várias considerações ao implantar e dar suporte a um cluster de avaliação:

* Você só pode usar o cluster para fins de avaliação. Não use um cluster com licença de avaliação em um ambiente de produção.
* Você deve usar o utilitário de administração ONTAP Select Deploy da seguinte maneira ao configurar cada host:
+
** Não forneça um número de série
** Configurar para usar uma licença de avaliação






== Características de licenciamento

A licença de avaliação ONTAP Select tem as seguintes características:

* Não é necessária uma licença de produção com capacidade de armazenamento
* O número de série do nó tem vinte dígitos e é gerado automaticamente pelo ONTAP Select Deploy
+
(você não o adquire diretamente da NetApp)

* O período de avaliação previsto na licença pode ser de até 90 dias
* O armazenamento máximo alocado por cada nó é o mesmo de uma licença de produção




== Atualizar para uma licença de produção

Você pode atualizar um cluster de avaliação do ONTAP Select para usar uma licença de produção. Esteja ciente das seguintes restrições:

* Você deve usar o utilitário de administração Deploy para executar a atualização da licença
* Você pode usar uma licença Capacity Tier, no entanto, o licenciamento Capacity Pools não é suportado
* Cada nó deve ter armazenamento suficiente alocado para suportar o mínimo necessário para uma licença de produção, com base no tamanho do cluster


Verlink:task_adm_licenses.html["Converter uma licença de avaliação em uma licença de produção"] para mais informações.

.Informações relacionadas
* link:concept_lic_production.html["Saiba mais sobre licenças para implantações de produção"]
* link:deploy-evaluation-ontap-select-ovf-template.html["Implantar uma instância de avaliação de 90 dias de um cluster ONTAP Select"]

