---
sidebar: sidebar 
permalink: reference_plan_ots_robo.html 
keywords: plan, planning, remote and branch office, robo 
summary: 'Você pode implantar o ONTAP Select em um ambiente de escritório remoto/filial (ROBO). Como parte do planejamento de uma implantação ROBO, você deve selecionar a configuração que atenda aos seus objetivos.' 
---
= Implantações remotas e de filiais da ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode implantar o ONTAP Select em um ambiente de escritório remoto/filial (ROBO). Como parte do planejamento de uma implantação ROBO, você deve selecionar a configuração que atenda aos seus objetivos.

Há duas configurações principais disponíveis ao implantar o ONTAP Select em um ambiente ROBO.


NOTE: Você pode usar qualquer licença do VMware vSphere ao implantar o ONTAP Select.

.ONTAP Select com ONTAP HA
O cluster de dois nós ONTAP Select consiste em um par de HA e é ideal para implantações ROBO.

.ONTAP Select com suporte VMware
Você pode implantar um cluster de nó único ONTAP Select em um ambiente ROBO. Embora um nó único não tenha capacidade nativa de alta disponibilidade, você pode implantar o cluster de uma das seguintes maneiras para fornecer proteção de armazenamento:

* Armazenamento externo compartilhado usando VMware HA
* VMware vSAN



NOTE: Se você usar o vSAN, precisará ter uma licença VMware vSAN ROBO.
