---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: A versão atual inclui vários novos recursos ou melhorias específicas do ONTAP Select. 
---
= Novidades do ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre os novos recursos e aprimoramentos nas versões suportadas do ONTAP Select.



== ONTAP Select 9.17.1

O ONTAP Select 9.17.1 inclui vários novos recursos e melhorias.

Suporte RAID de software para discos NVMe conectados localmente em hosts KVM:: O ONTAP Select 9.17.1 apresenta suporte RAID de software para discos NVMe ONTAP Select conectados localmente em um host de hipervisor de máquina virtual baseada em kernel (KVM).
+
--
Para usar RAID por software em discos NVMe conectados localmente, você precisa delink:kvm-host-configuration-and-preparation-checklist.html["configurar passagem PCI (DirectPath IO)"] quando você estiver preparando o host KVM. Isso fornece acesso direto do host KVM aos discos NVMe conectados localmente, o que é necessário para as seguintes tarefas:

* Configurando o host KVM para usar unidades NVMe
* Usando RAID de software após implantar o cluster


link:concept_stor_swraid_local.html["Saiba mais sobre os serviços de configuração RAID de software para armazenamento local conectado"].

--
Suporte para expansão e contração de cluster em hosts KVM:: A partir do ONTAP Select 9.17.1, o recurso de expansão e contração de cluster é compatível com máquinas virtuais baseadas em kernel (KVM) e hosts de hipervisor ESXi. Para o ONTAP Select 9.16.1 e 9.15.1, a expansão e contração de cluster são compatíveis apenas com hosts de hipervisor ESXi.
+
--
Você pode usar o recurso de expansão e contração de cluster em um cluster ONTAP Select existente para aumentar o tamanho de um cluster de seis nós para um cluster de oito nós ou diminuir o tamanho de um cluster de oito nós para um cluster de seis nós.

link:task_cluster_expansion_contraction.html["Saiba mais sobre expansão e contração de cluster e as versões de hipervisor KVM e ESXi suportadas"].

--
Suporte aprimorado para expansão e contração de cluster em hosts ESXi:: A partir do ONTAP Select 9.17.1, a expansão e a contração de clusters são suportadas para clusters de seis e doze nós em hosts ESXi:
+
--
--
Você pode aumentar o tamanho do cluster de um cluster ESXi existente nos seguintes incrementos:

* De seis nós para oito, dez ou doze nós
* De oito nós para dez ou doze nós
* De dez a doze nós


Você pode diminuir o tamanho do cluster de um cluster ESXi existente nos seguintes incrementos:

* De doze nós para dez, oito ou seis nós
* De dez nós para oito ou seis nós
* De oito a seis nós


--
link:task_cluster_expansion_contraction.html["Saiba mais sobre expansão e contração de cluster e as versões de hipervisor KVM e ESXi suportadas"].

--
Suporte para nuvem SnapMirror:: A partir do ONTAP Select 9.17.1, o SnapMirror Cloud é compatível com o ONTAP Select. O SnapMirror Cloud é um recurso licenciado do ONTAP que é habilitado por padrão ao implantar um cluster do ONTAP Select 9.17.1 ou atualizar um cluster do ONTAP Select existente para a versão 9.17.1.
+
--
https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["Saiba mais sobre backups em nuvem do SnapMirror para armazenamento de objetos"^].

--
Suporte para SnapLock Select Enterprise:: A partir do ONTAP Select 9.17.1, novas implementações têm o SnapLock Select Enterprise (incluindo o bloqueio de snapshots à prova de adulteração) licenciado automaticamente.  Para atualizações do ONTAP Select 9.16.1 e versões anteriores, você precisa baixar a licença do SnapLock Select do site [inserir link aqui].link:https://mysupport.netapp.com/site/["Site de suporte da NetApp"^] e aplicá-lo manualmente.
Suporte para vSAN ESA em clusters de vários nós:: A partir do ONTAP Select 9.17.1, o suporte para vSAN Express Storage Architecture (ESA) foi estendido para implantar clusters de vários nós. Esse aprimoramento permite que você implante configurações do vSAN ESA.
+
--
O vSAN ESA é uma configuração específica do ESX e é uma nova arquitetura para o VMware vSAN introduzida no vSphere 8. O vSAN ESA foi projetado para oferecer maior eficiência, escalabilidade e desempenho, especialmente ao usar dispositivos flash TLC baseados em NVMe.

O ONTAP Select Deploy e o ONTAP Select para ESX oferecem suporte à configuração de um cluster de nó único e de vários nós do ONTAP Select , usando um vSAN ou um tipo de matriz externa de armazenamento de dados para seu pool de armazenamento.

[NOTE]
====
Para executar operações na biblioteca de conteúdo, você precisará de acesso a níveis de permissão adicionais. Isso é necessário para implantações do vSAN ESA se você estiver trabalhando com funções restritas.

link:https://docs.netapp.com/us-en/ontap-select/reference_plan_dep_vmware.html["Saiba mais sobre como acessar níveis de permissão para operações de biblioteca de conteúdo"^].

====
--
Suporte atualizado ao driver NDA:: A partir do ONTAP Select 9.17.1, o driver de dispositivo FreeBSD NDA (NVMe Direct Access) substitui o NVD (NVMe Express Disk Driver). O driver FreeBSD oferece suporte para dispositivos de acesso direto implementando o protocolo de comando NVMe. Ao implantar um cluster ONTAP Select 9.17.1 ou atualizar um cluster ONTAP Select existente para a versão 9.17.1, o driver FreeBSD é iniciado por padrão ao configurar os dispositivos NVMe.
+
--
Para o ONTAP Select 9.16.1 e versões anteriores, o NVD continua a fornecer suporte para dispositivos NVMe na sua implantação do ONTAP Select .

--
Suporte atualizado ao hipervisor KVM:: A partir do ONTAP Select 9.17.1, o hipervisor KVM é suportado no Red Hat Enterprise Linux (RHEL) 10.0 e 9.6 e no Rocky Linux 10.0 e 9.6.


[NOTE]
====
Existem limitações de fluxo de trabalho RAID por software para hipervisores KVM em hosts RHEL 10.0 e Rocky Linux 10.0. Para obter mais informações, consulte os seguintes artigos da Base de Conhecimento:

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: Mensagem de aviso ao criar o Cluster HWR usando RHEL 10 e ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: Pools de armazenamento e discos de armazenamento não visíveis para SWR na página de criação de cluster em hosts com RHEL10/Rocky 10"^]


====
Suporte aprimorado ao VMware ESXi:: O ONTAP Select 9.17.1 inclui suporte para VMware ESXi 9.0.




== ONTAP Select 9.16.1

O ONTAP Select 9.16.1 inclui vários novos recursos e melhorias.

Suporte atualizado ao arquivo de licença NetApp:: A partir do ONTAP Select 9.16.1, o suporte ao Arquivo de Licença NetApp (NLF) foi atualizado. O novo formato NLF inclui licenças para os recursos ARP, ONTAP S3 e S3 SnapMirror . link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["Saber mais"].
+
--
Para uma nova implantação do ONTAP Select 9.16.1, o novo formato NLF é aplicado automaticamente. Ao atualizar uma implantação do ONTAP Select existente para a versão 9.16.1, o novo formato NLF não é aplicado. Para obter as licenças de recursos do ARP, ONTAP S3 e S3 SnapMirror , você precisa baixar o NLF atualizado após a atualização. Se você reverter para o ONTAP Select 9.15.1 ou anterior, precisará reinstalar as licenças de recursos que tinha antes da atualização.

--
Suporte para proteção autônoma contra ransomware:: O ONTAP Select 9.16.1 introduz suporte para Proteção Autônoma contra Ransomware (ARP). O ONTAP Select 9.16.1 suporta apenas atualizações manuais para ARP, atualizações automáticas não são suportadas. A licença do recurso ARP está incluída no NLF do ONTAP Select 9.16.1. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["Saber mais"].
Suporte aprimorado ao VMware ESXi:: O ONTAP Select 9.16.1 inclui suporte para VMware ESXi 8.0 U3.
Suporte atualizado ao hipervisor KVM:: A partir do ONTAP Select 9.16.1, o hipervisor KVM é compatível com RHEL 9.5 e Rocky Linux 9.5.




== ONTAP Select 9.15.1

O ONTAP Select 9.15.1 inclui vários novos recursos e melhorias.

Suporte atualizado ao hipervisor KVM:: A partir do ONTAP Select 9.15.1, o hipervisor de máquina virtual baseada em kernel (KVM) é compatível com RHEL 9.4 e Rocky Linux 9.4.
Apoio à expansão e contração de clusters:: A partir do ONTAP Select 9.15.1, a expansão e a contração de cluster são suportadas.
+
--
* Expansão de cluster de seis para oito nós
+
Você pode aumentar o tamanho do cluster de seis para oito nós com o recurso de expansão de cluster. Expansões de cluster de um, dois ou quatro nós para seis ou oito nós não são suportadas atualmente. link:task_cluster_expansion_contraction.html#expand-the-cluster["Saber mais"].

* Contração de cluster de oito a seis nós
+
Você pode reduzir o tamanho do cluster de oito para seis nós com o recurso de contração de cluster. Atualmente, não há suporte para contrações de clusters de seis ou oito nós para clusters de um, dois ou quatro nós. link:task_cluster_expansion_contraction.html#contract-the-cluster["Saber mais"].



--



NOTE: O suporte para expansão e contração de clusters é limitado somente a clusters ESX.



== ONTAP Select 9.14.1

O ONTAP Select 9.14.1 inclui vários novos recursos e melhorias.

Suporte para hipervisor KVM:: A partir do ONTAP Select 9.14.1, o suporte ao hipervisor KVM foi restabelecido. Anteriormente, o suporte para a implantação de um novo cluster em um hipervisor KVM foi removido no ONTAP Select 9.10.1, e o suporte para o gerenciamento de clusters e hosts KVM existentes, exceto para desativá-los ou excluí-los, foi removido no ONTAP Select 9.11.1.
A implantação do plug-in VMware vCenter não é mais suportada:: A partir do ONTAP Select 9.14.1, o plug-in Deploy VMware vCenter não é mais suportado.
Suporte atualizado ao ONTAP Select Deploy:: Se você estiver executando uma versão do ONTAP Select Deploy 9.14.1 anterior à 9.14.1P2, atualize para o ONTAP Select Deploy 9.14.1P2 o mais rápido possível. Para mais informações, consulte olink:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Notas de versão do ONTAP Select 9.14.1"^] .
Suporte aprimorado ao VMware ESXi:: O ONTAP Select 9.14.1 inclui suporte para VMware ESXi 8.0 U2.




== ONTAP Select 9.13.1

O ONTAP Select 9.13.1 inclui vários novos recursos e melhorias.

Suporte para NVMe sobre TCP:: Ao atualizar para o ONTAP Select 9.13.1, você precisa ter a nova licença para oferecer suporte a NVMe sobre TCP. Esta licença é incluída automaticamente ao implantar o ONTAP Select pela primeira vez a partir da versão 9.13.1.
Suporte VMware ESXi atualizado:: A partir do ONTAP 9.13.1, o VMware ESXi 8.0.1 GA (compilação 20513097) é compatível com a versão de hardware 4 e posteriores.
Suporte atualizado ao ONTAP Select Deploy:: A partir de abril de 2024, o ONTAP Select Deploy 9.13.1 não estará mais disponível no site de suporte da NetApp . Se você estiver executando o ONTAP Select Deploy 9.13.1, atualize para o ONTAP Select Deploy 9.14.1P2 o mais breve possível. Para mais informações, consulte olink:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Notas de versão do ONTAP Select 9.14.1"^] .




== ONTAP Select 9.12.1

O ONTAP Select 9.12.1 se beneficia da maioria dos novos desenvolvimentos da versão atual do produto principal do ONTAP . Ele não inclui novos recursos ou melhorias específicas do ONTAP Select.

A partir de abril de 2024, o ONTAP Select Deploy 9.12.1 não estará mais disponível no site de suporte da NetApp . Se você estiver executando o ONTAP Select Deploy 9.12.1, atualize para o ONTAP Select Deploy 9.14.1P2 o mais breve possível. Para mais informações, consulte olink:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Notas de versão do ONTAP Select 9.14.1"^] .



== ONTAP Select 9.11.1

O ONTAP Select 9.11.1 inclui vários novos recursos e melhorias.

Suporte aprimorado ao VMware ESXi:: O ONTAP Select 9.11.1 inclui suporte para VMware ESXi 7.0 U3C.
Suporte para VMware NSX-T:: O ONTAP Select 9.10.1 e versões posteriores foram qualificados para o VMware NSX-T versão 3.1.2. Não há problemas ou deficiências funcionais ao usar o NSX-T com um cluster de nó único do ONTAP Select implantado com um arquivo OVA e o utilitário de administração ONTAP Select Deploy. No entanto, ao usar o NSX-T com um cluster de vários nós do ONTAP Select , observe a seguinte limitação do ONTAP Select 9.11.1:
+
--
* Verificador de conectividade de rede
+
O verificador de conectividade de rede disponível por meio do Deploy CLI falha quando executado em uma rede baseada em NSX-T.



--
O hipervisor KVM não é mais suportado::
+
--
* A partir do ONTAP Select 9.10.1, não é mais possível implantar um novo cluster no hipervisor KVM.
* A partir do ONTAP Select 9.11.1, todas as funcionalidades de gerenciamento não estão mais disponíveis para clusters e hosts KVM existentes, exceto as funções de desativação e exclusão.
+
A NetApp recomenda fortemente que os clientes planejem e executem uma migração completa de dados do ONTAP Select para KVM para qualquer outra plataforma ONTAP , incluindo o ONTAP Select para ESXi. Para obter mais informações, consulte o https://mysupport.netapp.com/info/communications/ECMLP2877451.html["Aviso de EOA"^]



--




== ONTAP Select 9.10.1

O ONTAP Select 9.10.1 inclui vários novos recursos e melhorias.

Suporte para VMware NSX-T:: O ONTAP Select 9.10.1 foi qualificado para o VMware NSX-T versão 3.1.2. Não há problemas ou deficiências funcionais ao usar o NSX-T com um cluster de nó único do ONTAP Select implantado com um arquivo OVA e o utilitário de administração ONTAP Select Deploy. No entanto, ao usar o NSX-T com um cluster de vários nós do ONTAP Select , observe os seguintes requisitos e limitações:
+
--
* MTU de cluster
+
Você deve ajustar manualmente o tamanho da MTU do cluster para 8.800 antes de implantar o cluster para compensar a sobrecarga adicional. A orientação da VMware é permitir um buffer de 200 bytes ao usar o NSX-T.

* Configuração de rede 4x10Gb
+
Para implantações do ONTAP Select em um host VMware ESXi configurado com quatro NICs, o utilitário de implantação solicitará que você siga a prática recomendada de dividir o tráfego interno em dois grupos de portas diferentes e o tráfego externo em dois grupos de portas diferentes. No entanto, ao usar uma rede sobreposta, essa configuração não funciona e você deve desconsiderar a recomendação. Nesse caso, você deve usar apenas um grupo de portas internas e um grupo de portas externas.

* Verificador de conectividade de rede
+
O verificador de conectividade de rede disponível por meio do Deploy CLI falha quando executado em uma rede baseada em NSX-T.



--
O hipervisor KVM não é mais suportado:: A partir do ONTAP Select 9.10.1, não é mais possível implantar um novo cluster no hipervisor KVM. No entanto, se você atualizar um cluster de uma versão anterior para a 9.10.1, ainda poderá usar o utilitário de implantação para administrá-lo.




== ONTAP Select 9.9.1

O ONTAP Select 9.9.1 inclui vários novos recursos e melhorias.

Suporte à família de processadores:: A partir do ONTAP Select 9.9.1, somente modelos de CPU Intel Xeon Sandy Bridge ou posterior são suportados pelo ONTAP Select.
Suporte VMware ESXi atualizado:: O suporte ao VMware ESXi foi aprimorado com o ONTAP Select 9.9.1. As seguintes versões agora são suportadas:
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

Há vários recursos novos e alterados incluídos no ONTAP Select 9.8.

Interface de alta velocidade:: O recurso de interface de alta velocidade aprimora a conectividade de rede, oferecendo opções para 25G (25GbE) e 40G (40GbE). Para obter o melhor desempenho ao usar essas velocidades mais altas, siga as práticas recomendadas para configurações de mapeamento de portas, conforme descrito na documentação do ONTAP Select .
Suporte VMware ESXi atualizado:: Há duas mudanças no ONTAP Select 9.8 em relação ao suporte ao VMware ESXi.
+
--
* O ESXi 7.0 é compatível (compilação GA 15843807 e posterior)
* O ESXi 6.0 não é mais suportado


--

