---
sidebar: sidebar 
permalink: reference_api_workflow01.html 
keywords: rest api, deploy rest api, rest, workflow, create cluster, curl, json 
summary: Você pode implantar um cluster ONTAP Select de nó único em um host VMware ESXi gerenciado pelo vCenter. O cluster é criado com uma licença de avaliação. 
---
= Fluxo de trabalho 1: criar um cluster de avaliação de nó único ONTAP Select no ESXi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode implantar um cluster ONTAP Select de nó único em um host VMware ESXi gerenciado pelo vCenter. O cluster é criado com uma licença de avaliação.

O fluxo de trabalho de criação de cluster difere nas seguintes situações:

* O host ESXi não é gerenciado pelo vCenter (host autônomo)
* Vários nós ou hosts são usados dentro do cluster
* O cluster é implantado em um ambiente de produção com uma licença adquirida
* O hipervisor KVM é usado em vez do VMware ESXi




== 1. Registre a credencial do servidor vCenter

Ao implantar em um host ESXi gerenciado por um servidor vCenter, você deve adicionar uma credencial antes de registrar o host. O utilitário de administração de implantação pode então usar a credencial para autenticar no vCenter.

[cols="15,15,70"]
|===
| Categoria | verbo HTTP | Caminho 


| Implantar | PUBLICAR | /segurança/credenciais 
|===
Cachos::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step01 'https://10.21.191.150/api/security/credentials'
----
Entrada JSON (etapa 01)::


[source, json]
----
{
  "hostname": "vcenter.company-demo.com",
  "type": "vcenter",
  "username": "misteradmin@vsphere.local",
  "password": "mypassword"
}
----
Tipo de processamento:: Assíncrono
Saída::
+
--
* ID da credencial no cabeçalho de resposta de localização
* Objeto de trabalho


--




== 2. Registre um host do hipervisor

Você deve adicionar um host do hipervisor onde a máquina virtual que contém o nó ONTAP Select será executada.

[cols="15,15,70"]
|===
| Categoria | verbo HTTP | Caminho 


| Conjunto | PUBLICAR | /anfitriões 
|===
Cachos::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step02 'https://10.21.191.150/api/hosts'
----
Entrada JSON (etapa 02)::


[source, json]
----
{
  "hosts": [
    {
      "hypervisor_type": "ESX",
      "management_server": "vcenter.company-demo.com",
      "name": "esx1.company-demo.com"
    }
  ]
}
----
Tipo de processamento:: Assíncrono
Saída::
+
--
* ID do host no cabeçalho de resposta de localização
* Objeto de trabalho


--




== 3. Crie um cluster

Quando você cria um cluster ONTAP Select , a configuração básica do cluster é registrada e os nomes dos nós são gerados automaticamente pelo Deploy.

[cols="15,15,70"]
|===
| Categoria | verbo HTTP | Caminho 


| Conjunto | PUBLICAR | /clusters 
|===
Cachos:: O parâmetro de consulta node_count deve ser definido como 1 para um cluster de nó único.


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step03 'https://10.21.191.150/api/clusters? node_count=1'
----
Entrada JSON (etapa 03)::


[source, json]
----
{
  "name": "my_cluster"
}
----
Tipo de processamento:: Síncrono
Saída::
+
--
* ID do cluster no cabeçalho de resposta de localização


--




== 4. Configurar o cluster

Há vários atributos que você deve fornecer como parte da configuração do cluster.

[cols="15,15,70"]
|===
| Categoria | verbo HTTP | Caminho 


| Conjunto | CORREÇÃO | /clusters/{id_do_cluster} 
|===
Cachos:: Você deve fornecer o ID do cluster.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step04 'https://10.21.191.150/api/clusters/CLUSTERID'
----
Entrada JSON (etapa 04)::


[source, json]
----
{
  "dns_info": {
    "domains": ["lab1.company-demo.com"],
    "dns_ips": ["10.206.80.135", "10.206.80.136"]
    },
    "ontap_image_version": "9.5",
    "gateway": "10.206.80.1",
    "ip": "10.206.80.115",
    "netmask": "255.255.255.192",
    "ntp_servers": {"10.206.80.183"}
}
----
Tipo de processamento:: Síncrono
Saída:: Nenhum




== 5. Recupere o nome do nó

O utilitário de administração Deploy gera automaticamente os identificadores e nomes dos nós quando um cluster é criado. Antes de configurar um nó, você precisa recuperar o ID atribuído.

[cols="15,15,70"]
|===
| Categoria | verbo HTTP | Caminho 


| Conjunto | PEGAR | /clusters/{cluster_id}/nós 
|===
Cachos:: Você deve fornecer o ID do cluster.


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/clusters/CLUSTERID/nodes?fields=id,name'
----
Tipo de processamento:: Síncrono
Saída::
+
--
* A matriz registra cada um descrevendo um único nó com ID e nome exclusivos


--




== 6. Configurar os nós

Você deve fornecer a configuração básica para o nó, que é a primeira das três chamadas de API usadas para configurar um nó.

[cols="15,15,70"]
|===
| Categoria | verbo HTTP | Caminho 


| Conjunto | CAMINHO | /clusters/{id_do_cluster}/nós/{id_do_nó} 
|===
Cachos:: Você deve fornecer o ID do cluster e o ID do nó.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step06 'https://10.21.191.150/api/clusters/CLUSTERID/nodes/NODEID'
----
Entrada JSON (etapa 06):: Você deve fornecer o ID do host onde o nó ONTAP Select será executado.


[source, json]
----
{
  "host": {
    "id": "HOSTID"
    },
  "instance_type": "small",
  "ip": "10.206.80.101",
  "passthrough_disks": false
}
----
Tipo de processamento:: Síncrono
Saída:: Nenhum




== 7. Recupere as redes de nós

Você deve identificar as redes de dados e gerenciamento usadas pelo nó no cluster de nó único. A rede interna não é usada com um cluster de nó único.

[cols="15,15,70"]
|===
| Categoria | verbo HTTP | Caminho 


| Conjunto | PEGAR | /clusters/{id_do_cluster}/nós/{id_do_nó}/redes 
|===
Cachos:: Você deve fornecer o ID do cluster e o ID do nó.


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/ clusters/CLUSTERID/nodes/NODEID/networks?fields=id,purpose'
----
Tipo de processamento:: Síncrono
Saída::
+
--
* Matriz de dois registros, cada um descrevendo uma única rede para o nó, incluindo o ID exclusivo e a finalidade


--




== 8. Configurar a rede do nó

Você deve configurar as redes de dados e gerenciamento. A rede interna não é usada com um cluster de nó único.


NOTE: Emita a seguinte chamada de API duas vezes, uma para cada rede.

[cols="15,15,70"]
|===
| Categoria | verbo HTTP | Caminho 


| Conjunto | CORREÇÃO | /clusters/{id_do_cluster}/nós/{id_do_nó}/redes/{id_da_rede} 
|===
Cachos:: Você deve fornecer o ID do cluster, o ID do nó e o ID da rede.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step08 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID/networks/NETWORKID'
----
Entrada JSON (etapa 08):: Você precisa fornecer o nome da rede.


[source, json]
----
{
  "name": "sDOT_Network"
}
----
Tipo de processamento:: Síncrono
Saída:: Nenhum




== 9. Configurar o pool de armazenamento de nós

A etapa final na configuração de um nó é anexar um pool de armazenamento. Você pode determinar os pools de armazenamento disponíveis por meio do cliente web do vSphere ou, opcionalmente, por meio da API REST de implantação.

[cols="15,15,70"]
|===
| Categoria | verbo HTTP | Caminho 


| Conjunto | CORREÇÃO | /clusters/{id_do_cluster}/nós/{id_do_nó}/redes/{id_da_rede} 
|===
Cachos:: Você deve fornecer o ID do cluster, o ID do nó e o ID da rede.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step09 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID'
----
Entrada JSON (etapa 09):: A capacidade do pool é de 2 TB.


[source, json]
----
{
  "pool_array": [
    {
      "name": "sDOT-01",
      "capacity": 2147483648000
    }
  ]
}
----
Tipo de processamento:: Síncrono
Saída:: Nenhum




== 10. Implantar o cluster

Depois que o cluster e o nó forem configurados, você poderá implantar o cluster.

[cols="15,15,70"]
|===
| Categoria | verbo HTTP | Caminho 


| Conjunto | PUBLICAR | /clusters/{cluster_id}/implantar 
|===
Cachos:: Você deve fornecer o ID do cluster.


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step10 'https://10.21.191.150/api/clusters/CLUSTERID/deploy'
----
Entrada JSON (etapa 10):: Você deve fornecer a senha para a conta de administrador do ONTAP .


[source, json]
----
{
  "ontap_credentials": {
    "password": "mypassword"
  }
}
----
Tipo de processamento:: Assíncrono
Saída::
+
--
* Objeto de trabalho


--


.Informações relacionadas
link:deploy-evaluation-ontap-select-ovf-template.html["Implantar uma instância de avaliação de 90 dias de um cluster ONTAP Select"]
