---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: Há várias questões de planejamento relacionadas ao armazenamento do host ONTAP Select que você deve considerar. 
---
= Considerações sobre armazenamento e RAID do ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Há várias questões de planejamento relacionadas ao armazenamento do host ONTAP Select que você deve considerar.


NOTE: As informações sobre suporte a armazenamento externo estão descritas emlink:reference_plan_ots_vnas.html["Requisitos do ONTAP Select vNAS"] .



== Requisitos do controlador RAID de hardware

O controlador RAID no host do hipervisor onde você implanta o ONTAP Select deve atender a vários requisitos.


NOTE: Um host onde o ONTAP Select é executado requer unidades físicas locais ao usar um controlador RAID de hardware ou o recurso RAID de software fornecido com o ONTAP Select. Se você usar a solução vNAS do ONTAP Select para acessar armazenamento externo, um controlador RAID local e o recurso RAID de software não serão usados.

Os requisitos mínimos para o controlador RAID incluem:

* Taxa de transferência de 12 Gbps
* 512 MB de cache interno com bateria ou flash (SuperCAP)
* Configurado no modo write-back:
+
** Habilitar o modo de failback para “gravar” (se compatível)
** Habilitar a política “sempre ler à frente” (se compatível)


* Todos os discos locais atrás do controlador RAID devem ser configurados como um único grupo RAID; vários controladores RAID podem ser usados, se necessário:
+
** Desabilite o cache da unidade local para o grupo RAID, o que é fundamental para preservar a integridade dos dados.


* A configuração do LUN deve ser realizada com base nas seguintes diretrizes:
+
** Se o tamanho do grupo RAID exceder o tamanho máximo de LUN de 64 TB, você deverá configurar vários LUNs de tamanho igual consumindo todo o armazenamento disponível dentro do grupo RAID.
** Se o tamanho do grupo RAID for menor que o tamanho máximo do LUN de 64 TB, você deverá configurar um LUN consumindo todo o armazenamento disponível dentro do grupo RAID.






== Requisitos de RAID de software

Ao implantar um cluster ONTAP Select no hipervisor, você pode utilizar o recurso RAID de software fornecido pelo ONTAP Select em vez de um controlador RAID de hardware local. Há vários requisitos e restrições que você deve conhecer antes de implantar um cluster usando RAID de software.



=== Requisitos gerais

O ambiente para uma implantação de RAID de software deve atender aos seguintes requisitos principais:

* VMware ESXi 7.0 GA (compilação 15843807) ou posterior
* ONTAP Select ou superior
* Somente unidades SSD locais
* Separação dos discos do sistema da raiz e dos agregados de dados
* Nenhum controlador RAID de hardware no host



NOTE: Se houver um controlador RAID de hardware, consulte olink:concept_stor_concepts_chars.html["Armazenamento de mergulho profundo"] seção para requisitos de configuração adicionais.



=== Requisitos específicos do ESXi

* VMware ESXi 7.0 GA (compilação 15843807) ou posterior
* VMware VMotion, HA e DRS não são suportados
* Não é possível usar RAID por software com um nó que tenha sido atualizado do ONTAP Select 9.4 ou anterior. Nesse caso, você precisará criar um novo nó para implantação de RAID por software.




=== Requisitos específicos do KVM

Existem também requisitos específicos de configuração de pacotes de software. Veja olink:https://docs.netapp.com/us-en/ontap-select/kvm-host-configuration-and-preparation-checklist.html#prepare-linux-server["preparação do servidor Linux"] Para mais informações, clique aqui.

Expectativas da mídia para KVM:: Os dispositivos de armazenamento flash SSD utilizados devem atender aos seguintes requisitos adicionais:
+
--
* Os dispositivos SSD devem se reportar de forma precisa e persistente ao host Linux por meio dos seguintes métodos:
+
** # cat /sys/block/<dispositivo>/queue/rotational
+
O valor relatado para esses comandos deve ser '0'.



* Espera-se que os dispositivos estejam conectados a um HBA ou, em alguns casos, a um controlador RAID configurado para operar em modo JBOD. Ao usar um controlador RAID, a função do dispositivo deve ser passada pelo host sem sobrepor nenhuma funcionalidade RAID. Ao usar um controlador RAID em modo JBOD, você deve revisar a documentação do RAID ou entrar em contato com o fornecedor, conforme necessário, para garantir que o dispositivo informe a velocidade de rotação como "0".
* Existem dois componentes de armazenamento separados:
+
** Armazenamento de máquina virtual
+
Este é um pool LVM (pool de armazenamento) que contém os dados do sistema usados para hospedar a máquina virtual ONTAP Select . O pool LVM deve ser suportado por um dispositivo flash de alta resistência, podendo ser SAS, SATA ou NVMe. Um dispositivo NVMe é recomendado para melhor desempenho.

** Discos de dados
+
Este é um conjunto de unidades SSD SAS ou SATA usadas para gerenciamento de dados. Os dispositivos SSD devem ser de nível empresarial e duráveis. A interface NVMe não é compatível.



* Todos os dispositivos devem ser formatados com 512 BPS.


--




=== Configuração do nó ONTAP Select

Você deve configurar cada nó ONTAP Select e host do hipervisor da seguinte maneira para separar os discos do sistema da raiz e dos agregados de dados:

* Criar um pool de armazenamento do sistema. Você deve criar um pool de armazenamento para os dados do sistema ONTAP Select . Você deve anexar o pool de armazenamento como parte da configuração do nó ONTAP Select .
* Anexe os discos físicos necessários. O host do hipervisor deve ter os discos SSD necessários conectados e disponíveis para uso pela máquina virtual ONTAP Select . Essas unidades contêm os agregados raiz e de dados. Você deve anexar os discos de armazenamento como parte da configuração do nó ONTAP Select .




== Restrições de capacidade de armazenamento

Como parte do planejamento de uma implantação do ONTAP Select , você deve estar ciente das restrições relacionadas à alocação e ao uso do armazenamento.

As restrições de armazenamento mais importantes são apresentadas a seguir. Você também deve revisar olink:https://mysupport.netapp.com/matrix/["Ferramenta de Matriz de Interoperabilidade"^] Para obter informações mais detalhadas.


TIP: O ONTAP Select impõe diversas restrições relacionadas à alocação e ao uso do armazenamento. Antes de implantar um cluster ONTAP Select ou adquirir uma licença, você deve se familiarizar com essas restrições. Veja olink:https://docs.netapp.com/us-en/ontap-select/concept_lic_evaluation.html["Licença"] Para mais informações, consulte a seção abaixo.



=== Calcular capacidade de armazenamento bruta

A capacidade de armazenamento do ONTAP Select corresponde ao tamanho total permitido dos dados virtuais e discos raiz conectados à máquina virtual ONTAP Select . Você deve considerar isso ao alocar capacidade.



=== Capacidade mínima de armazenamento para um cluster de nó único

O tamanho mínimo do pool de armazenamento alocado para o nó em um cluster de nó único é:

* Avaliação: 500 GB
* Produção: 1,0 TB


A alocação mínima para uma implantação de produção consiste em 1 TB para dados do usuário, mais aproximadamente 266 GB usados por vários processos internos do ONTAP Select , o que é considerado sobrecarga necessária.



=== Capacidade mínima de armazenamento para um cluster multinó

O tamanho mínimo do pool de armazenamento alocado para cada nó em um cluster de vários nós é:

* Avaliação: 1,9 TB
* Produção: 2,0 TB


A alocação mínima para uma implantação de produção consiste em 2 TB para dados do usuário, mais aproximadamente 266 GB usados por vários processos internos do ONTAP Select , o que é considerado sobrecarga necessária.

[NOTE]
====
Cada nó em um par HA deve ter a mesma capacidade de armazenamento.

Ao estimar a quantidade de armazenamento para um par de HA, você deve considerar que todos os agregados (raiz e dados) são espelhados. Como resultado, cada plexo do agregado consome a mesma quantidade de armazenamento.

Por exemplo, quando um agregado de 2 TB é criado, ele aloca 2 TB para duas instâncias plex (2 TB para plex0 e 2 TB para plex1) ou 4 TB da quantidade total licenciada de armazenamento.

====


=== Capacidade de armazenamento e múltiplos pools de armazenamento

Você pode configurar cada nó do ONTAP Select para usar até 400 TB de armazenamento ao usar armazenamento de conexão direta local, VMware vSAN ou matrizes de armazenamento externas. No entanto, um único pool de armazenamento tem um tamanho máximo de 64 TB ao usar armazenamento de conexão direta ou matrizes de armazenamento externas. Portanto, se você planeja usar mais de 64 TB de armazenamento nessas situações, deve alocar vários pools de armazenamento da seguinte forma:

* Atribuir o pool de armazenamento inicial durante o processo de criação do cluster
* Aumente o armazenamento do nó alocando um ou mais pools de armazenamento adicionais



NOTE: Um buffer de 2% é deixado sem uso em cada pool de armazenamento e não requer uma licença de capacidade. Esse armazenamento não é usado pelo ONTAP Select, a menos que um limite de capacidade seja especificado. Se um limite de capacidade for especificado, essa quantidade de armazenamento será usada, a menos que a quantidade especificada se enquadre na zona de buffer de 2%. O buffer é necessário para evitar erros ocasionais que ocorrem ao tentar alocar todo o espaço em um pool de armazenamento.



=== Capacidade de armazenamento e VMware vSAN

Ao usar o VMware vSAN, um armazenamento de dados pode ter mais de 64 TB. No entanto, você só pode alocar inicialmente até 64 TB ao criar o cluster ONTAP Select . Após a criação do cluster, você pode alocar armazenamento adicional do armazenamento de dados vSAN existente. A capacidade do armazenamento de dados vSAN que pode ser consumida pelo ONTAP Select é baseada no conjunto de políticas de armazenamento da VM.



=== Melhores práticas

Você deve considerar as seguintes recomendações em relação ao hardware do núcleo do hipervisor:

* Todas as unidades em um único agregado ONTAP Select devem ser do mesmo tipo. Por exemplo, você não deve misturar unidades de HDD e SSD no mesmo agregado.




== Requisitos adicionais de unidade de disco com base na licença da plataforma

As unidades que você escolher serão limitadas com base na oferta de licença da plataforma.


NOTE: Os requisitos de unidade de disco se aplicam ao uso de um controlador e unidades RAID locais, bem como RAID por software. Esses requisitos não se aplicam ao armazenamento externo acessado por meio da solução ONTAP Select vNAS.

.Padrão
* 8 a 60 HDDs internos (NL-SAS, SATA, 10K SAS)


.Prêmio
* 8 a 60 HDDs internos (NL-SAS, SATA, 10K SAS)
* 4 a 60 SSDs internos


.Premium XL
* 8 a 60 HDDs internos (NL-SAS, SATA, 10K SAS)
* 4 a 60 SSDs internos
* 4 a 14 NVMe internos



NOTE: O RAID de software com unidades DAS locais é compatível com a licença premium (somente SSD) e a licença premium XL (SSD ou NVMe).



== Unidades NVMe com RAID de software

Você pode configurar o RAID de software para usar unidades SSD NVMe. Seu ambiente deve atender aos seguintes requisitos:

* ONTAP Select com um utilitário de administração Deploy compatível
* Oferta de licença de plataforma XL Premium ou uma licença de avaliação de 90 dias
* VMware ESXi versão 6.7 ou posterior
* Dispositivos NVMe em conformidade com a especificação 1.0 ou posterior


Você precisa configurar manualmente as unidades NVMe antes de usá-las. Verlink:task_chk_nvme_configure.html["Configurar um host para usar unidades NVMe"] para mais informações.
