---
sidebar: sidebar 
permalink: reference_plan_dep_vmware.html 
keywords: plan, planning, ontap select deploy, vmware requirements 
summary: Há vários requisitos e restrições específicos ao ambiente VMware que você deve considerar antes de instalar o utilitário ONTAP Select Deploy em um ambiente VMware. 
---
= Considerações sobre o host do hipervisor ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Há várias questões de planejamento relacionadas ao host do hipervisor que você deve considerar.


CAUTION: Você não deve modificar diretamente a configuração de uma máquina virtual ONTAP Select, a menos que seja instruído a fazê-lo pelo suporte da NetApp . Uma máquina virtual só deve ser configurada e modificada por meio do utilitário de administração Deploy. Fazer alterações em uma máquina virtual ONTAP Select fora do utilitário Deploy sem a assistência do suporte da NetApp pode causar falhas na máquina virtual e torná-la inutilizável.



== Independente do hipervisor

Tanto o ONTAP Select quanto o utilitário de administração ONTAP Select Deploy são independentes do hipervisor.

Os seguintes hipervisores são suportados pela administração do ONTAP Select e do ONTAP Select Deploy:

* VMware ESXi
* Máquina Virtual Baseada em Kernel (KVM)



NOTE: Consulte as informações de planejamento específicas do hipervisor e as notas de versão para obter detalhes adicionais sobre as plataformas suportadas.

.Hypervisor para ONTAP Select nós e utilitário de administração
Tanto o utilitário de administração Deploy quanto os nós ONTAP Select são executados como máquinas virtuais. O hipervisor escolhido para o utilitário Deploy é independente do hipervisor escolhido para os nós ONTAP Select . Você tem total flexibilidade ao emparelhar os dois:

* O utilitário de implantação em execução no VMware ESXi pode criar e gerenciar clusters ONTAP Select no VMware ESXi ou KVM
* O utilitário de implantação em execução no KVM pode criar e gerenciar clusters ONTAP Select no VMware ESXi ou KVM


.Uma ou mais instâncias do nó ONTAP Select por host
Cada nó do ONTAP Select é executado como uma máquina virtual dedicada. Você pode criar vários nós no mesmo host do hipervisor, com as seguintes restrições:

* Vários nós de um único cluster ONTAP Select não podem ser executados no mesmo host. Todos os nós em um host específico devem ser de clusters ONTAP Select diferentes.
* Você deve usar armazenamento externo.
* Se você usar RAID de software, poderá implantar apenas um nó ONTAP Select no host.


.Consistência do hipervisor para os nós dentro de um cluster
Todos os hosts dentro de um cluster ONTAP Select devem ser executados na mesma versão e liberação do software do hipervisor.

.Número de portas físicas em cada host
Você deve configurar cada host para usar uma, duas ou quatro portas físicas. Embora haja flexibilidade na configuração das portas de rede, você deve seguir estas recomendações sempre que possível:

* Um host em um cluster de nó único deve ter duas portas físicas.
* Cada host em um cluster de vários nós deve ter quatro portas físicas


.Integrar o ONTAP Select com um cluster baseado em hardware ONTAP
Não é possível adicionar um nó ONTAP Select diretamente a um cluster ONTAP baseado em hardware. No entanto, você pode, opcionalmente, estabelecer um relacionamento de peering de cluster entre um cluster ONTAP Select e um cluster ONTAP baseado em hardware.



== Ambiente de hipervisor VMware

Há vários requisitos e restrições específicos ao ambiente VMware que você deve considerar antes de instalar o utilitário ONTAP Select Deploy em um ambiente VMware.

.Requisitos de hardware do servidor host ESXi
Existem vários requisitos mínimos de recursos que o seu host do hipervisor ESXi deve atender. Você deve garantir que os hosts onde o ONTAP Select está implantado atendam aos seguintes requisitos básicos:

* Servidor ESXi:
+
** O hardware e o software devem ser de 64 bits
** Deve aderir às mesmas versões suportadas definidas para um nó ONTAP Select


* CPUs virtuais (2)
* Memória virtual (4 GB)
* Armazenamento (40 GB)
* DHCP habilitado (também pode atribuir um endereço IP estático)


.Conectividade de rede
Você deve certificar-se de que a interface de rede da máquina virtual ONTAP Select Deploy esteja configurada e tenha um único endereço IP de gerenciamento. Você pode usar o DHCP para atribuir um endereço IP dinamicamente ou configurar manualmente um endereço IP estático.

Dependendo das suas decisões de implantação, a VM de implantação deve ser capaz de se conectar ao servidor vCenter, aos hosts do hipervisor ESXi e aos nós ONTAP Select que gerencia. Você deve configurar seus firewalls para permitir o tráfego necessário.

O Deploy utiliza a API VMware VIX para se comunicar com o servidor vCenter e os hosts ESXi. Inicialmente, ele estabelece uma conexão usando SOAP sobre SSL na porta TCP 443. Em seguida, uma conexão é aberta usando SSL na porta 902. Além disso, o Deploy emite comandos PING para verificar se há um host ESXi no endereço IP especificado.

O Deploy também deve ser capaz de se comunicar com os endereços IP de gerenciamento de cluster e nó do ONTAP Select usando os seguintes protocolos:

* Comando PING (ICMP)
* SSH (porta 22)
* SSL (porta 443)


.Suporte para IP versão 4
O ONTAP Select Deploy suporta apenas a versão 4 do IP (IPv4). A versão 6 do IP (IPv6) não é suportada. Essa restrição afeta o ONTAP Select das seguintes maneiras:

* Você deve atribuir um endereço IPv4 ao LIF de gerenciamento da máquina virtual de implantação.
* O Deploy não pode criar nós ONTAP Select configurados para usar IPv6 nos LIFs ONTAP .




== Considerações sobre a implantação do servidor VMware vCenter do ONTAP Select



=== Privilégios do VMware vSphere para ESA

A seguir estão listados os privilégios específicos para a biblioteca de conteúdo do vSphere necessários para criar e gerenciar o vSAN Express Storage Architecture (ESA) no vCenter:

* Adicionar item de biblioteca
* Criar biblioteca local
* Excluir item da biblioteca
* Excluir biblioteca local
* Armazenamento de leitura
* Atualizar arquivos
* Atualizar biblioteca
* Atualizar item da biblioteca
* Atualizar biblioteca local

