---
sidebar: sidebar 
permalink: reference_plan_ots_vnas.html 
keywords: plan, planning, vnas, vmware esxi, 
summary: Há várias questões de planejamento relacionadas ao uso do VMware ESXi que você deve considerar. 
---
= Requisitos do ONTAP Select VMware ESXi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select vNAS é uma solução que permite que os armazenamentos de dados do ONTAP Select sejam externos ao host do hipervisor ESXi onde a máquina virtual do ONTAP Select é executada. Esses armazenamentos de dados remotos podem ser acessados por meio do VMware vSAN ou de um array de armazenamento externo genérico.



== Requisitos básicos e restrições

A solução ONTAP Select vNAS pode ser usada com um cluster ONTAP Select de qualquer tamanho.

Todos os componentes de armazenamento relacionados, incluindo hardware, software e requisitos de recursos, devem estar em conformidade com os requisitos descritos no documento.link:https://mysupport.netapp.com/matrix/["Ferramenta de Matriz de Interoperabilidade"^] . o ONTAP Select oferece suporte a todos os conjuntos de armazenamento externo descritos na documentação de compatibilidade VMware Storage/SAN, incluindo iSCSI, NAS (NFSv3), Fibre Channel e Fibre Channel sobre Ethernet. O suporte a conjuntos externos é limitado pela versão do ESXi suportada pelo ONTAP Select.

Os seguintes recursos do VMware são suportados ao implantar um cluster com o ONTAP Select vNAS:

* VMotion
* Alta Disponibilidade (HA)
* Agendador de Recursos Distribuídos (DRS)



NOTE: Esses recursos do VMware são compatíveis com clusters ONTAP Select de nó único e de vários nós. Ao implantar um cluster de vários nós, certifique-se de que dois ou mais nós do mesmo cluster não sejam executados no mesmo host do hipervisor.

Os seguintes recursos do VMware não são suportados:

* Tolerância a Falhas (FT)
* Armazenamento de dados virtual (VVOL)




== Requisitos de configuração

Se você planeja usar um repositório de dados VMFS em um conjunto de armazenamento externo (iSCSI, Fibre Channel, Fibre Channel sobre Ethernet), crie um pool de armazenamento VMFS antes de configurar o ONTAP Select para usar o armazenamento. Se você usar um repositório de dados NFS, não há necessidade de criar um repositório de dados VMFS separado. Todos os repositórios de dados vSAN devem ser definidos no mesmo cluster ESXi.


CAUTION: Você deve fornecer um limite de capacidade para cada armazenamento de dados no VMware vSAN ou em um conjunto de armazenamento externo ao configurar um host ou executar uma operação de adição de armazenamento. A capacidade especificada deve estar dentro dos limites de armazenamento permitidos do armazenamento externo. Ocorrerá um erro se você não fornecer um limite de capacidade ou se o armazenamento externo ficar sem espaço durante a operação de criação do disco.



== Melhores práticas

Consulte a documentação disponível da VMware e siga as práticas recomendadas aplicáveis identificadas para hosts ESXi. Além disso:

* Definir portas de rede dedicadas, largura de banda e configurações de vSwitch para as redes ONTAP Select e armazenamento externo (tráfego de matriz de armazenamento genérico e VMware vSAN ao usar iSCSI ou NFS)
* Configure a opção de capacidade para restringir a utilização do armazenamento (o ONTAP Select não pode consumir toda a capacidade de um armazenamento de dados vNAS externo)
* Garantir que todos os conjuntos de armazenamento externo genérico usem os recursos de redundância e HA disponíveis sempre que possível

