---
sidebar: sidebar 
permalink: task_api_understanding_call.html 
keywords: rest api, deploy rest api, rest, understanding, executing 
summary: Os detalhes de todas as chamadas de API são documentados e exibidos em um formato comum na página de documentação online do ONTAP Select Deploy. Ao compreender uma única chamada de API, você pode acessar e interpretar os detalhes de todas as chamadas de API. 
---
= Entenda e execute uma chamada de API ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Os detalhes de todas as chamadas de API são documentados e exibidos em um formato comum na página de documentação online do ONTAP Select Deploy. Ao compreender uma única chamada de API, você pode acessar e interpretar os detalhes de todas as chamadas de API.

.Antes de começar
Você precisa estar conectado à página de documentação online do ONTAP Select Deploy. Você precisa ter o identificador exclusivo atribuído ao seu cluster ONTAP Select quando ele foi criado.

.Sobre esta tarefa
Você pode recuperar as informações de configuração que descrevem um cluster ONTAP Select usando seu identificador exclusivo. Neste exemplo, todos os campos classificados como baratos são retornados. No entanto, como prática recomendada, você deve solicitar apenas os campos específicos necessários.

.Passos
. Na página principal, role até o final e clique em *Cluster*.
. Clique em *GET /clusters/{cluster_id}* para exibir os detalhes da chamada de API usada para retornar informações sobre um cluster ONTAP Select .

