---
sidebar: sidebar 
permalink: task_cli_migrate_deploy.html 
keywords: administer, administering, cli, deploy, deploy instance, migrate 
summary: Você pode migrar uma instância existente do utilitário de administração Deploy para uma nova máquina virtual usando a interface de linha de comando. 
---
= Migrar uma instância do ONTAP Select Deploy para uma nova máquina virtual
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode migrar uma instância existente do utilitário de administração Deploy para uma nova máquina virtual usando a interface de linha de comando.

Este procedimento baseia-se na criação de uma nova máquina virtual que utiliza os dados de configuração da máquina virtual original. As máquinas virtuais nova e original devem executar a mesma versão e lançamento do utilitário de implantação. Não é possível migrar para uma versão e lançamento diferentes do utilitário de implantação.



== Passo 1: Faça backup dos dados de configuração de implantação.

Você deve criar um backup dos dados de configuração de implantação como parte da migração da máquina virtual. Você também deve criar um backup após a implantação de um cluster ONTAP Select . Os dados são salvos em um único arquivo criptografado que você pode baixar para sua estação de trabalho local.

.Antes de começar
* Certifique-se de que o Deploy não esteja executando nenhuma outra tarefa durante a operação de backup.
* Salve a imagem original da máquina virtual Deploy.
+

CAUTION: A imagem original da máquina virtual de implantação será necessária posteriormente neste procedimento quando você restaurar os dados de configuração de implantação da máquina virtual original para a nova.



.Sobre esta tarefa
O arquivo de backup criado captura todos os dados de configuração da máquina virtual. Esses dados descrevem aspectos do seu ambiente de implantação, incluindo os clusters ONTAP Select .

.Passos
. Sign in na CLI do utilitário Deploy usando SSH com a conta de administrador.
. Crie um backup dos dados de configuração do Deploy, que são armazenados em um diretório interno no servidor Deploy:
+
[source, cli]
----
deploy backup create
----
. Forneça uma senha para o backup quando solicitado.
+
O arquivo de backup é criptografado com base na senha.

. Exibir os backups disponíveis no sistema:
+
[source, cli]
----
deploy backup show -detailed
----
. Selecione seu arquivo de backup com base na data no campo *Criado* e registre o valor *URL de download*.
+
Você pode acessar o arquivo de backup através do URL.

. Usando um navegador da web ou um utilitário como o Curl, baixe o arquivo de backup para sua estação de trabalho local com o URL.




== Etapa 2: Instale uma nova instância da máquina virtual de implantação.

Você deve criar uma nova instância da máquina virtual Deploy que pode ser atualizada com os dados de configuração da máquina virtual original.

.Antes de começar
Você deve estar familiarizado com os procedimentos usados para baixar e implantar a máquina virtual ONTAP Select Deploy em um ambiente VMware.

.Sobre esta tarefa
Esta tarefa é descrita em alto nível.

.Passos
. Crie uma nova instância da máquina virtual Deploy:
+
.. Baixe a imagem da máquina virtual.
.. Implante a máquina virtual e configure a interface de rede.
.. Acesse o utilitário Deploy usando SSH.




.Informações relacionadas
link:task_install_deploy.html["Instalar ONTAP Select Implantar"]



== Etapa 3: Restaure os dados de configuração de implantação para a nova máquina virtual.

Você deve restaurar os dados de configuração da máquina virtual original do utilitário de implantação para a nova máquina virtual. Os dados estão em um único arquivo que você deve carregar da sua estação de trabalho local.

.Antes de começar
Você deve ter os dados de configuração de um backup anterior. Os dados estão contidos em um único arquivo e devem estar disponíveis na sua estação de trabalho local.

.Passos
. Em um terminal de comando em sua estação de trabalho local, use o utilitário sftp para enviar o arquivo de backup para a máquina virtual de implantação, conforme mostrado no exemplo a seguir:
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put deploy_backup_20190601162151.tar.gz
exit
....
. Sign in na CLI do utilitário Deploy usando SSH com a conta de administrador.
. Restaurar os dados de configuração:
+
[source, cli]
----
deploy backup restore -path <path_name> -filename <file_name>
----
+
Comando de exemplo

+
`deploy backup restore -path /home/admin -filename deploy_backup_20180601162151.tar.gz`


